spring.application.name=pia
spring.profiles.active=local

#spotify.client.id=${SPOTIFY_CLIENT_ID}
#spotify.client.secret=${SPOTIFY_CLIENT_SECRET}

server.port=8080

# Neon PostgreSQL


spring.datasource.url=jdbc:postgresql://ep-twilight-shadow-ai8shxxi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rcDUa8K0Xbmy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.connection-timeout=20000
#spring.datasource.hikari.max-lifetime=600000
#spring.datasource.hikari.keepalive-time=300000

# JWT
jwt.secret=UxAVIDK73llJfpd0KE4oDNPOnG8w79l0YAKRs8bpYMz
jwt.expiration=86400000
