spring.application.name=pia
spring.profiles.active=local

# Spotify API
spotify.client.id=50f26a82452c47afae65f81bf6b4803d
spotify.client.secret=895f62d91f294fada702ceb57edad448

server.port=8080

# Last.fm
lastfm.api.key=79f266a2a05533e8e8c8725f2d56ae4c
lastfm.base.url=http://ws.audioscrobbler.com/2.0/

# Neon PostgreSQL


spring.datasource.url=jdbc:postgresql://ep-twilight-shadow-ai8shxxi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rcDUa8K0Xbmy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.connection-timeout=20000
#spring.datasource.hikari.max-lifetime=600000
#spring.datasource.hikari.keepalive-time=300000

# JWT
jwt.secret=UxAVIDK73llJfpd0KE4oDNPOnG8w79l0YAKRs8bpYMz
jwt.expiration=86400000
